Added a fix for normalizing imports from more than one level of parent modules (issue/2152)
PyCQA/isort pull request #2191
Opened 2023-10-21 18:29 UTC by bp72

Closes #2152

2023-12-04 18:37 UTC, staticdev commented on isort/identify.py
> +from isort.parse import _strip_syntax, normalize_line, skip_line
Following the same logic, I would rename `_strip_syntax` to `strip_syntax`. It will be better if you could also do it ;)

2023-12-04 18:37 UTC, staticdev requested changes
Thanks for your PR @bp72 do you mind checking the suggestion I made?

2023-12-09 14:48 UTC, bp72 commented
@staticdev sorry, missed the comment :) It's renamed now.

2023-12-10 14:58 UTC, staticdev approved these changes

2023-12-10 14:59 UTC, merged

2023-12-10 14:59 UTC, staticdev commented
Thanks @bp72, LGTM.