nit: Fix deprecation message link
PyCQA/isort pull request #2220
Opened 2024-01-04 09:11 UTC by syou6162

The following warning message was outputting a link that was not valid, so it has been corrected to a valid link.

```
/Users/yasuhisa.yoshida/.cache/pre-commit/repoclpuwaei/py_env-python3.10/lib/python3.10/site-packages/isort/settings.py:343: UserWarning: A custom settings file was specified: /Users/yasuhisa.yoshida/10xinc/stailer-hermes/pyproject.toml but no configuration was found inside. This can happen when [settings] is used as the config header instead of [isort]. See: https://pycqa.github.io/isort/docs/configuration/config_files/#custom_config_files for more information.
  warn(
```

2024-01-14 15:30 UTC, syou6162 commented
@staticdev Could you review this pull request?

2024-02-11 18:57 UTC, syou6162 commented
@bp72 Thank you for reviewing! 

@staticdev Could you merge this pull request?

2025-01-14 20:23 UTC, DanielNoord requested changes

2025-01-14 20:23 UTC, DanielNoord commented on isort/settings.py
> +                    "#custom_config_files for more information."
```suggestion
                    "#custom-config-files for more information."
```

This is the new pattern.

2025-01-14 20:48 UTC, DanielNoord approved these changes

2025-01-20 11:44 UTC, merged